// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwjXk_ECUYYtiaFiqipV61JtiYAA3Pks0',
    appId: '1:638838664523:web:5b4e1a28379b5499aeccce',
    messagingSenderId: '638838664523',
    projectId: 'friendly-faces-29a8d',
    authDomain: 'friendly-faces-29a8d.firebaseapp.com',
    storageBucket: 'friendly-faces-29a8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeSft0kgMvvGFAqr6S1OEas-bU6dCjRmU',
    appId: '1:638838664523:ios:ade256827672ae47aeccce',
    messagingSenderId: '638838664523',
    projectId: 'friendly-faces-29a8d',
    storageBucket: 'friendly-faces-29a8d.appspot.com',
    androidClientId:
        '638838664523-nltrnk4vnkomu167civolt0o1p2ob4dh.apps.googleusercontent.com',
    iosClientId:
        '638838664523-6n8nve3vs0g4o8r2mb5ub93g7nh8sgjq.apps.googleusercontent.com',
    iosBundleId: 'com.example.friendlyFaces',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeSft0kgMvvGFAqr6S1OEas-bU6dCjRmU',
    appId: '1:638838664523:ios:ade256827672ae47aeccce',
    messagingSenderId: '638838664523',
    projectId: 'friendly-faces-29a8d',
    storageBucket: 'friendly-faces-29a8d.appspot.com',
    androidClientId:
        '638838664523-nltrnk4vnkomu167civolt0o1p2ob4dh.apps.googleusercontent.com',
    iosClientId:
        '638838664523-6n8nve3vs0g4o8r2mb5ub93g7nh8sgjq.apps.googleusercontent.com',
    iosBundleId: 'com.example.friendlyFaces',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeSft0kgMvvGFAqr6S1OEas-bU6dCjRmU',
    appId: '1:638838664523:ios:ade256827672ae47aeccce',
    messagingSenderId: '638838664523',
    projectId: 'friendly-faces-29a8d',
    storageBucket: 'friendly-faces-29a8d.appspot.com',
    androidClientId:
        '638838664523-nltrnk4vnkomu167civolt0o1p2ob4dh.apps.googleusercontent.com',
    iosClientId:
        '638838664523-6n8nve3vs0g4o8r2mb5ub93g7nh8sgjq.apps.googleusercontent.com',
    iosBundleId: 'com.example.friendlyFaces',
  );
}
